/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlMultiple;
import Controlador.CtlUnica;
import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author Yo
 */
public class FrmBuscarPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form FrmBuscarPreguntas
     */
    CtlMultiple controladorMultiple = new CtlMultiple();
    CtlUnica controladorUnica = new CtlUnica();
    String cadena = "";

    public FrmBuscarPreguntas() {
        initComponents();
        jTableBuscar.getTableHeader().setFont(new Font("Gill Sans Ultra Bold Condensed", 0, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuscar = new javax.swing.JTable();
        txtTemaBuscar = new javax.swing.JTextField();
        txtEnunciadoBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        jLabel1.setText("Enunciado:");

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        jLabel2.setText("Codigo tema:");

        jTableBuscar.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jTableBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "TEMA", "ENUNCIADO"
            }
        ));
        jScrollPane1.setViewportView(jTableBuscar);

        txtTemaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaBuscarActionPerformed(evt);
            }
        });
        txtTemaBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTemaBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTemaBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTemaBuscarKeyTyped(evt);
            }
        });

        txtEnunciadoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnunciadoBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTemaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtEnunciadoBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTemaBuscar)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEnunciadoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaBuscarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTemaBuscarActionPerformed

    private void txtTemaBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemaBuscarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTemaBuscarKeyPressed

    private void txtTemaBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemaBuscarKeyTyped

    }//GEN-LAST:event_txtTemaBuscarKeyTyped

    private void txtTemaBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemaBuscarKeyReleased
        ArrayList<String> buscar = new ArrayList<>();
        buscar = controladorMultiple.solicitudBuscarFiltrado(txtTemaBuscar.getText(), "tema_idtema");
        buscar = controladorUnica.solicitudBuscarFiltrado(txtTemaBuscar.getText(), "tema_idtema");
        listar(buscar);
    }//GEN-LAST:event_txtTemaBuscarKeyReleased

    private void txtEnunciadoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnunciadoBuscarKeyReleased
        ArrayList<String> buscar = new ArrayList<>();
        buscar = controladorMultiple.solicitudBuscarFiltrado(txtEnunciadoBuscar.getText(), "enunciado");
        buscar = controladorUnica.solicitudBuscarFiltrado(txtEnunciadoBuscar.getText(), "enunciado");
        
        listar(buscar);
    }//GEN-LAST:event_txtEnunciadoBuscarKeyReleased
    
    private void listar(ArrayList<String> buscar) {
        jTableBuscar.setModel(controladorMultiple.listarM(buscar));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuscar;
    private javax.swing.JTextField txtEnunciadoBuscar;
    private javax.swing.JTextField txtTemaBuscar;
    // End of variables declaration//GEN-END:variables
}
